// Writes the Stats page's OFFLINE FALLBACK snapshot (site spec 004, T011). The page reads
// /api/grounnel/stats live; this is only what it renders when that call fails.
import { writeFileSync } from "node:fs";
import { buildStatsSnapshot } from "../src/services/stats.service";

const OUT = "../frontend/src/data/stats.ts";

async function main() {
  const snapshot = await buildStatsSnapshot();
  writeFileSync(
    OUT,
    [
      "// Generated by biassemble/backend/scripts/generate-stats.ts. Aggregates only — no run text,",
      "// no claim text, no cost or token figures. Regenerate, don't edit.",
      "",
      "export interface StatsSnapshot {",
      "  generatedAt: string;",
      "  window: { from: string; to: string };",
      "  productionRuns: number;",
      "  evalRuns: number;",
      "  promptVersions: { extract: string; verify: string }[];",
      "  verdicts: { verdict: string; n: number }[];",
      "  totalClaims: number;",
      "}",
      "",
      `const stats: StatsSnapshot = ${JSON.stringify(snapshot, null, 2)};`,
      "",
      "export default stats;",
      "",
    ].join("\n"),
  );
  console.log(
    `${snapshot.productionRuns} production runs (${snapshot.window.from}..${snapshot.window.to}), ` +
      `${snapshot.evalRuns} eval runs, ${snapshot.totalClaims} claims → ${OUT}`,
  );
  process.exit(0);
}

main();
