/**
 * Build script: fetches JSON Schema contracts from the AI Core service
 * and generates TypeScript type definitions.
 *
 * Run: pnpm generate:types
 * Output: src/lib/ai/contracts.ts
 *
 * Prerequisites: AI Core must be running (pnpm dev in biassemble-core).
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const CORE_URL = process.env.CORE_URL ?? "http://localhost:8000";
const API_KEY = process.env.CORE_API_KEY ?? "dev-key";
const OUT = resolve(import.meta.dirname, "..", "src", "lib", "ai", "contracts.generated.ts");

interface SchemaBundle {
  reflection: Record<string, Record<string, unknown>>;
}

async function main() {
  console.log(`Fetching contracts from ${CORE_URL}/v1/contracts ...`);

  const res = await fetch(`${CORE_URL}/v1/contracts`, {
    headers: { Authorization: `Bearer ${API_KEY}` },
    signal: AbortSignal.timeout(10_000),
  });

  if (!res.ok) {
    throw new Error(`Failed to fetch contracts: ${res.status} ${res.statusText}`);
  }

  const bundle: SchemaBundle = await res.json();
  const lines: string[] = [
    "// ⚠️ AUTO-GENERATED — DO NOT EDIT",
    "// Generated by `pnpm generate:types` from AI Core contracts endpoint.",
    "// Run this script whenever the Zod schemas in biassemble-core change.",
    "// This file contains ONLY TypeScript interfaces. Zod schemas live in contracts.ts.",
    "",
    "// ─── Reflection Contracts ───────────────────────────────",
    "",
  ];

  for (const [name, schema] of Object.entries(bundle.reflection)) {
    const ts = await compile(schema as any, name, {
      bannerComment: "",
      strictIndexSignatures: true,
      additionalProperties: false,
    });
    lines.push(ts);
    lines.push("");
  }

  writeFileSync(OUT, lines.join("\n"), "utf-8");
  console.log(`✓ Types written to ${OUT}`);
}

main().catch((err) => {
  console.error("Failed to generate types:", err);
  process.exit(1);
});