// Writes the Stats page's OFFLINE FALLBACK snapshot (site spec 004, T011). The page reads
// /api/grounnel/stats live; this is only what it renders when that call fails.
import { writeFileSync } from "node:fs";
import { buildStatsSnapshot } from "../src/services/stats.service";

const OUT = "../frontend/src/data/stats.ts";

async function main() {
  const snapshot = await buildStatsSnapshot();
  // Refuse rather than overwrite: a null window means this database has no production runs (a
  // fresh or wrong one), and committing that would replace a good fallback with an empty page.
  if (!snapshot.window) {
    console.error(`Refusing to write ${OUT}: no production runs found. Wrong database?`);
    process.exit(1);
  }
  // Only the fields the FRONTEND contract declares, listed explicitly. A field added to the
  // backend type would otherwise land in a file the frontend type-checks, breaking its build.
  const fallback = {
    generatedAt: snapshot.generatedAt,
    window: snapshot.window,
    productionRuns: snapshot.productionRuns,
    evalRuns: snapshot.evalRuns,
    promptVersions: snapshot.promptVersions,
    verdicts: snapshot.verdicts,
    totalClaims: snapshot.totalClaims,
  };
  writeFileSync(
    OUT,
    [
      "// Generated by biassemble/backend/scripts/generate-stats.ts. Aggregates only — no run text,",
      "// no claim text, no cost or token figures. Regenerate, don't edit.",
      "import type { StatsSnapshot } from '../types/stats';",
      "",
      `const stats: StatsSnapshot = ${JSON.stringify(fallback, null, 2)};`,
      "",
      "export default stats;",
      "",
    ].join("\n"),
  );
  console.log(
    `${snapshot.productionRuns} production runs (${snapshot.window.from}..${snapshot.window.to}), ` +
      `${snapshot.evalRuns} eval runs, ${snapshot.totalClaims} claims → ${OUT}`,
  );
  process.exit(0);
}

main();
