// ⚠️ AUTO-GENERATED — DO NOT EDIT
// Generated by `pnpm generate:types` from biassemble-core/contracts/reflection.schemas.json.
// Run this script whenever the Zod schemas in biassemble-core change.
// These types mirror Core's reflection schemas exactly.

// ─── Core Reflection Contracts ─────────────────────────

export interface GenerateQuestionRequest {
  sessionId: string;
  story: string;
}


export interface GenerateAssessmentRequest {
  sessionId: string;
  story: string;
  /**
   * @minItems 1
   */
  questions: [string, ...string[]];
  /**
   * @minItems 1
   */
  answers: [string, ...string[]];
}


export interface QuestionOutput {
  /**
   * @minItems 2
   * @maxItems 5
   */
  questions:
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string];
  isComplete: boolean;
}


export interface AssessmentOutput {
  /**
   * @minItems 1
   */
  biases: [
    {
      name: string;
      explanation: string;
      storyConnection: string;
      alternativePerspective: string;
    },
    ...{
      name: string;
      explanation: string;
      storyConnection: string;
      alternativePerspective: string;
    }[]
  ];
  reflectionPrompt: string;
}


export interface BiasItem {
  name: string;
  explanation: string;
  storyConnection: string;
  alternativePerspective: string;
}

