/**
 * Build script: reads JSON Schema contracts from biassemble-core
 * and generates TypeScript type definitions.
 *
 * Run: pnpm generate:types
 * Output: src/types/api.generated.ts
 *
 * Source: biassemble-core/contracts/reflection.schemas.json
 * (same JSON served by Core's GET /v1/contracts and backend's GET /api/contracts)
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const SCHEMAS_JSON = resolve(
  import.meta.dirname,
  "..",
  "..",
  "..",
  "biassemble-core",
  "contracts",
  "reflection.schemas.json"
);
const OUT = resolve(import.meta.dirname, "..", "src", "types", "api.generated.ts");

interface SchemaBundle {
  reflection: Record<string, Record<string, unknown>>;
}

async function main() {
  console.log(`Reading schemas from ${SCHEMAS_JSON} ...`);
  const raw = readFileSync(SCHEMAS_JSON, "utf-8");
  const bundle: SchemaBundle = JSON.parse(raw);

  const lines: string[] = [
    "// ⚠️ AUTO-GENERATED — DO NOT EDIT",
    "// Generated by `pnpm generate:types` from biassemble-core/contracts/reflection.schemas.json.",
    "// Run this script whenever the Zod schemas in biassemble-core change.",
    "// These types mirror Core's reflection schemas exactly.",
    "",
    "// ─── Core Reflection Contracts ─────────────────────────",
    "",
  ];

  for (const [name, schema] of Object.entries(bundle.reflection)) {
    const ts = await compile(schema as any, name, {
      bannerComment: "",
      strictIndexSignatures: true,
      additionalProperties: false,
    });
    lines.push(ts);
    lines.push("");
  }

  writeFileSync(OUT, lines.join("\n"), "utf-8");
  console.log(`✓ Types written to ${OUT}`);
}

main().catch((err) => {
  console.error("Failed to generate types:", err);
  process.exit(1);
});
