// Generated by biassemble/backend/scripts/generate-stats.ts. Aggregates only — no run text,
// no claim text, no cost or token figures. Regenerate, don't edit.

export interface StatsSnapshot {
  generatedAt: string;
  window: { from: string; to: string };
  productionRuns: number;
  evalRuns: number;
  promptVersions: { extract: string; verify: string }[];
  verdicts: { verdict: string; n: number }[];
  totalClaims: number;
}

const stats: StatsSnapshot = {
  "generatedAt": "2026-09-09T10:50:01.848Z",
  "window": {
    "from": "2026-08-07",
    "to": "2026-09-08"
  },
  "productionRuns": 268,
  "evalRuns": 3207,
  "promptVersions": [
    {
      "extract": "1.7.0",
      "verify": "4.6.0"
    },
    {
      "extract": "1.6.0",
      "verify": "4.6.0"
    }
  ],
  "verdicts": [
    {
      "verdict": "supported",
      "n": 2692
    },
    {
      "verdict": "unsupported",
      "n": 459
    },
    {
      "verdict": "contradicted",
      "n": 271
    },
    {
      "verdict": "unverifiable",
      "n": 183
    },
    {
      "verdict": "excluded",
      "n": 135
    },
    {
      "verdict": "no_verdict",
      "n": 35
    },
    {
      "verdict": "partially_supported",
      "n": 29
    }
  ],
  "totalClaims": 3804
};

export default stats;
