// Generated by biassemble/backend/scripts/generate-stats.ts. Aggregates only — no run text,
// no claim text, no cost or token figures. Regenerate, don't edit.

export interface StatsSnapshot {
  generatedAt: string;
  window: { from: string; to: string };
  productionRuns: number;
  evalRuns: number;
  promptVersions: { extract: string; verify: string }[];
  verdicts: { verdict: string; n: number }[];
  totalClaims: number;
}

const stats: StatsSnapshot = {
  "generatedAt": "2026-09-10T18:42:20.442Z",
  "window": {
    "from": "2026-08-07",
    "to": "2026-09-10"
  },
  "productionRuns": 281,
  "evalRuns": 3207,
  "promptVersions": [
    {
      "extract": "1.7.0",
      "verify": "4.6.0"
    },
    {
      "extract": "1.6.0",
      "verify": "4.6.0"
    }
  ],
  "verdicts": [
    {
      "verdict": "supported",
      "n": 2809
    },
    {
      "verdict": "unsupported",
      "n": 540
    },
    {
      "verdict": "contradicted",
      "n": 273
    },
    {
      "verdict": "excluded",
      "n": 210
    },
    {
      "verdict": "unverifiable",
      "n": 205
    },
    {
      "verdict": "no_verdict",
      "n": 43
    },
    {
      "verdict": "partially_supported",
      "n": 29
    }
  ],
  "totalClaims": 4109
};

export default stats;
