// Generated by biassemble/backend/scripts/generate-stats.ts. Aggregates only — no run text,
// no claim text, no cost or token figures. Regenerate, don't edit.
import type { StatsSnapshot } from '../types/stats';

const stats: StatsSnapshot = {
  "generatedAt": "2026-09-10T19:37:39.157Z",
  "window": {
    "from": "2026-08-07",
    "to": "2026-09-10"
  },
  "productionRuns": 281,
  "evalRuns": 3207,
  "promptVersions": [
    {
      "extract": "1.7.0",
      "verify": "4.6.0"
    },
    {
      "extract": "1.6.0",
      "verify": "4.6.0"
    }
  ],
  "verdicts": [
    {
      "verdict": "supported",
      "n": 2809
    },
    {
      "verdict": "unsupported",
      "n": 540
    },
    {
      "verdict": "contradicted",
      "n": 273
    },
    {
      "verdict": "excluded",
      "n": 210
    },
    {
      "verdict": "unverifiable",
      "n": 205
    },
    {
      "verdict": "no_verdict",
      "n": 43
    },
    {
      "verdict": "partially_supported",
      "n": 29
    }
  ],
  "totalClaims": 4109
};

export default stats;
